Add matchAnchorWidth to popover
enigma-io/boundless pull request #39
Opened 2017-03-13 03:38 UTC by newyork-anthonyng

This commit is a WIP. 

I will add tests to this if this is the way to go.

2017-03-13 16:21 UTC, quantizor requested changes
Great start! Some comments attached.

2017-03-13 16:21 UTC, probablyup commented on packages/boundless-popover/index.js
> +      const anchor = this.props.anchor instanceof HTMLElement
Just learned this recently, but `findDOMNode` is actually a no-op if called on a DOM node, so you can remove this ternary and always call it.

2017-03-13 16:21 UTC, probablyup commented on packages/boundless-popover/index.js
> +      const anchorWidth = anchor.getBoundingClientRect().width;
We compute this in `cacheViewportCartography()` as called by `this.align()`, so if we move the invocation of this function to after the caching is complete, we can avoid doing the measurement work twice :smile:

2017-03-13 16:21 UTC, probablyup commented on packages/boundless-popover/index.js
> +        window.addEventListener('resize', this.matchAnchorWidth, true);
I think we can remove this additional event listener as well by integrating the width matching function into the alignment flow.

2017-03-17 03:17 UTC, newyork-anthonyng commented
@probablyup Thanks for the comments. I will make the updates and work on adding tests this weekend.

2017-03-20 00:38 UTC, newyork-anthonyng commented
I made the changes and added a test for this. Let me know if there's anything else needed :)

2017-06-06 04:50 UTC, quantizor approved these changes

2017-06-06 04:50 UTC, probablyup commented
Sorry for the very long delay, this looks excellent.

2017-06-06 04:51 UTC, merged